name: Build/release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Extend network timeout
        run: yarn config set network-timeout 300000

      - name: Setup Ubuntu dependencies
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          sudo apt update
          sudo apt install libudev-dev libusb-1.0-0-dev

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # Kick off the electron frontend compilation steps
          build_script_name: 'build:for:electron'

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: 'Upload macOS artifact'
        if: ${{ startsWith(matrix.os, 'macos-') }}
        uses: actions/upload-artifact@v2
        with:
          name: QMK-XAP_macOS.dmg.zip
          path: dist_electron/QMK XAP*.dmg
          if-no-files-found: error

      - name: 'Upload Linux artifact'
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        uses: actions/upload-artifact@v2
        with:
          name: QMK-XAP_Linux.AppImage.zip
          path: dist_electron/QMK XAP*.AppImage
          if-no-files-found: error

      - name: 'Upload Windows artifact'
        if: ${{ startsWith(matrix.os, 'windows-') }}
        uses: actions/upload-artifact@v2
        with:
          name: QMK-XAP_Windows.exe.zip
          path: dist_electron/QMK XAP*.exe
          if-no-files-found: error
